version: "3.8"

services:
    db:
        image: postgres:10
        container_name: db
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - HOST=db
        networks:
            - hunet2
        restart: unless-stopped
    redis:
        image: redis:7.0-alpine
        container_name: redis
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./redis/:/etc/redis/
        ports:
            - 6379:6379
        networks:
            - hunet2
        restart: unless-stopped
    api:
        build:
          context: ./backend
        container_name: api
        command: bash -c "python3 /code/manage.py migrate && python3 /code/manage.py runserver 0.0.0.0:8000 && /code/vendor/unoconv --listener"
        volumes:
            - /opt/eqa/:/opt/eqa
            - /tmp/:/tmp/
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - hunet2
        restart: unless-stopped
    celery:
        build:
          context: ./backend
        container_name: celery
        restart: always
        command: celery -A huqas_api.config worker -B -l info
        volumes:
            - /opt/eqa/:/opt/eqa
            - /tmp/:/tmp/
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
            - api
        networks:
            - hunet2

networks:
    hunet2:
        name: hunet2
        driver: bridge
