version: "3.9"

services:
    redis:
        image: redis:7.0-alpine
        container_name: redis
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./volumes/redis/:/etc/redis/
        ports:
            - 6379:6379
        networks:
            - mks
        restart: unless-stopped

    backend:
        build:
            context: ./backend
        container_name: easymed-backend
        # command: uvicorn --host 0.0.0.0 --port 8080 easymed.asgi:application
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./backend:/code
        ports:
            - 8080:8080
        env_file:
            - ./.env
        restart: unless-stopped
        networks:
            - mks

    worker:
        restart: unless-stopped
        build:
            context: ./backend
        volumes:
            - ./static_files:/app/easymed/static
        env_file:
            - ./.env    
        depends_on:
            - backend
            - redis
        networks:
            - mks   

    frontend:
        build:
            context: ./front-end
            dockerfile: ./Dockerfile.local
        container_name: easymed-frontend
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - backend
        volumes:
            - ./front-end:/app    
        networks:
            - mks    

networks:
    mks:
        name: mks
        driver: bridge
