version: "3.9"

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/django_static

    db:
        image: postgres:14
        container_name: db
        volumes:
            - ./data/db:/pgdata
        env_file:
            - ./.env    
        # environment:
        #     - POSTGRES_DB=postgres
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=postgres
        #     - HOST=db
        # networks:
        #     - mks
        restart: unless-stopped

    redis:
        image: redis:7.0-alpine
        container_name: redis2
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./redis/:/etc/redis/
        # ports:
        #     - 6379:6379
        # networks:
        #     - mks
        restart: unless-stopped

    backend:
        image: mosesmbadi/mkhmisbackend
        container_name: backend
        command: ./backend-entrypoint.sh
        volumes:
            - ./backend:/code/
        ports:
            - 8080:8080
        env_file:
            - ./.env
        depends_on:
            - db
        restart: unless-stopped
        # networks:
        #     - mks

    worker:
        restart: unless-stopped
        image: mosesmbadi/mkhmisbackend
        volumes:
            - static_volume:/app/backend/django_static
        env_file:
          - .env

        depends_on:
            - backend
            - redis
        # networks:
        #     - mks   

    frontend:
        image: mosesmbadi/mkhmisfrontend
        container_name: front-end
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - backend
        # networks:
        #     - mks    


volumes:
    static_volume: {}
    postgres_data: {}

# networks:
#     mks:
#         name: mks
#         driver: bridge
