version: '3.8'

services:
  backend:
    build: ./backend
    # command: gunicorn makeeasyhmis.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  frontend:
    build: ./front-end
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres_data: