name: CI

on:
  push:
    branches: [ dev-moses ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Print Docker Username
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"


      - name: Build and push backend image
        run: |
          cd app/backend
          docker build -t mosesmbadi/mkhmisbackend:latest .
          docker push mosesmbadi/mkhmisbackend:latest

      - name: Build and push frontend image
        run: |
          cd app/front-end
          docker build -t mosesmbadi/mkhmisfrontend:latest .
          docker push mosesmbadi/mkhmisfrontend:latest