name: CI

on:
  push:
    branches: [ dev-moses ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t mkhmis/backend:latest .
          docker push mkhmis/backend:latest

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t mkhmis/frontend:latest .
          docker push mkhmis/frontend:latest
